/**
 * Wallet-signed contract deployment. Bundles the audited VestingVault NEF
 * + manifest (see {@code nef-artifacts.ts}, generated by
 * {@code scripts/sync-artifacts.mjs}) and routes the
 * {@code ContractManagement.deploy} invocation through the connected
 * wallet.
 *
 * The resulting contract hash is *deterministic*: it's a function of the
 * deployer's script hash + the NEF checksum + the manifest name, so we can
 * compute it locally before the tx confirms (matching the formula
 * neow3j's {@code SmartContract.calcContractHash} uses on the Java side).
 */

import { sc, u, wallet } from '@cityofzion/neon-js';
import { NeonInvoker } from '@cityofzion/neon-dappkit';
import type { ContractInvocationMulti } from '@cityofzion/neon-dappkit-types';
import type { UnifiedProvider } from './connection';
import { NEF_BASE64, MANIFEST_JSON, ARTIFACTS_AVAILABLE } from './nef-artifacts';
import { EXPECTED_NEF_CHECKSUM } from './nef-checksum';
import { resolveRpcUrl } from './rpc';

/** Native ContractManagement script hash (the Neo system contract that owns deploy/update/destroy). */
const CONTRACT_MANAGEMENT = '0xfffdc93764dbaddd97c48f252a53ea4643faa3fd';

export interface DeployArgs {
  /** N-prefixed Neo3 address (or 0x scripthash) of the account paying for + signing the deploy. */
  deployerAddress: string;
  /** Address (or scripthash) that will own the new vault — the only one allowed to deposit. */
  ownerAddress: string;
}

export interface DeployResult {
  txHash: string;
  /** Locally computed; matches the on-chain hash exactly once the tx confirms. */
  contractHash: string;
}

export function isArtifactsAvailable(): boolean {
  return ARTIFACTS_AVAILABLE;
}

/**
 * Build the {@code ContractManagement.deploy} invocation payload — used by
 * both {@link deployVault} (which signs + sends) and {@link predictDeployFee}
 * (which test-invokes for fee estimation, no signature).
 */
export function buildDeployPayload(args: DeployArgs): ContractInvocationMulti {
  const ownerScriptHash = toScriptHash(args.ownerAddress);
  const deployerScriptHash = toScriptHash(args.deployerAddress);
  const nefHex = base64ToHex(NEF_BASE64);
  const manifestHex = u.str2hexstring(MANIFEST_JSON);

  // ContractManagement.deploy(nef, manifest, [optional data])
  // The third arg is forwarded as `data` to the new contract's _deploy callback.
  // The signer's `account` must be a hex scripthash — neon-dappkit's
  // calculateFee path goes through neon-js which rejects N-prefixed addresses
  // here. Wallet adapters accept either form, so converting is safe for both.
  return {
    invocations: [
      {
        scriptHash: CONTRACT_MANAGEMENT,
        operation: 'deploy',
        args: [
          { type: 'ByteArray', value: nefHex },
          { type: 'ByteArray', value: manifestHex },
          { type: 'Hash160', value: ownerScriptHash },
        ],
      },
    ],
    signers: [{ account: deployerScriptHash, scopes: 'CalledByEntry' }],
  };
}

/**
 * Submit the deploy. Returns the tx hash and the predicted contract hash;
 * caller awaits confirmation via {@link waitForTx}.
 */
export async function deployVault(provider: UnifiedProvider, args: DeployArgs): Promise<DeployResult> {
  if (!ARTIFACTS_AVAILABLE) {
    throw new Error(
      'No NEF/manifest bundled with this UI build. Run `./gradlew :contract:neow3jCompile` then rebuild.',
    );
  }

  const deployerScriptHash = toScriptHash(args.deployerAddress);
  const payload = buildDeployPayload(args);

  const result = await provider.invokeFunction(payload);
  const txHash = typeof result === 'string' ? result : (result as { hash: string }).hash;

  const contractHash = predictContractHash(deployerScriptHash, EXPECTED_NEF_CHECKSUM, getBundledManifestName());
  return { txHash, contractHash };
}

/**
 * Estimated deployment cost in raw GAS units (1 GAS = 10^8 raw). Returns
 * {@code null} if the RPC is unreachable or the test invoke fails (e.g.
 * the owner address is invalid). Decomposed into:
 *
 *   - {@code systemFee} — VM execution + per-byte storage cost.
 *     ContractManagement charges ~10 GAS for a contract this size.
 *   - {@code networkFee} — tx propagation, proportional to tx size.
 *
 * This is a real RPC call (test-invoke against ContractManagement.deploy);
 * the returned values match what the wallet will charge at signing time
 * within ~1% (small differences from witness-script estimation).
 */
export async function predictDeployFee(args: DeployArgs): Promise<DeployFee> {
  if (!ARTIFACTS_AVAILABLE) {
    throw new Error('No NEF/manifest bundled — recompile the contract and rebuild the UI.');
  }
  const invoker = await NeonInvoker.init({ rpcAddress: resolveRpcUrl() });
  const payload = buildDeployPayload(args);
  const fee = await invoker.calculateFee(payload);
  // neon-dappkit returns fees as decimal-GAS strings (e.g. "10.00157522"),
  // not raw integer units. Convert by shifting 8 decimal places.
  const sys = gasStringToRaw(fee.systemFee);
  const net = gasStringToRaw(fee.networkFee);
  return { systemFee: sys, networkFee: net, total: sys + net };
}

/** Convert a decimal-GAS string ("10.00157522") to raw units (1000157522n). */
function gasStringToRaw(s: string): bigint {
  const [whole, frac = ''] = String(s).split('.');
  const fracPadded = (frac + '00000000').slice(0, 8);
  return BigInt(whole) * 100_000_000n + BigInt(fracPadded);
}

export interface DeployFee {
  /** Raw GAS units (10^8 = 1 GAS). */
  systemFee: bigint;
  /** Raw GAS units. */
  networkFee: bigint;
  /** systemFee + networkFee, in raw GAS units. */
  total: bigint;
}

/** Format a raw-GAS fee as a human-readable "X.XXXX GAS" string. */
export function fmtGas(rawAmount: bigint): string {
  const decimals = 8n;
  const factor = 10n ** decimals;
  const whole = rawAmount / factor;
  const frac = rawAmount % factor;
  if (frac === 0n) return `${whole} GAS`;
  // Trim trailing zeros from the fractional part for compact display.
  const fracStr = frac.toString().padStart(Number(decimals), '0').replace(/0+$/, '');
  return `${whole}.${fracStr} GAS`;
}

/**
 * Re-implement {@code SmartContract.calcContractHash} from the Java side:
 *
 *   script = ABORT  ||  PUSHDATA1(20)(senderLE)  ||  PUSHINT(checksum)  ||  PUSHDATA1(name_len)(name)
 *   hash   = ripemd160(sha256(script))
 *
 * Returns the 20-byte hash as a 0x-prefixed big-endian hex string (Neo's
 * conventional display form).
 */
export function predictContractHash(
  senderScriptHash: string,
  nefChecksum: number,
  manifestName: string,
): string {
  const senderHex = stripHex(senderScriptHash);
  const senderLE = u.reverseHex(senderHex); // sender as little-endian bytes

  const sb = new sc.ScriptBuilder();
  sb.emit(sc.OpCode.ABORT);
  sb.emitPush(u.HexString.fromHex(senderLE));
  sb.emitPush(nefChecksum);
  sb.emitPush(manifestName);

  const scriptHex = sb.build();
  const hashLE = u.hash160(scriptHex);
  // u.hash160 returns big-endian already; but Neo's contract hashes are
  // displayed reversed-from-storage. Test against a known case if in doubt.
  return '0x' + u.reverseHex(hashLE);
}

/** Read the bundled manifest's `name` field. */
export function getBundledManifestName(): string {
  if (!MANIFEST_JSON) return '';
  try {
    return (JSON.parse(MANIFEST_JSON) as { name: string }).name;
  } catch {
    return '';
  }
}

/** Read the bundled NEF's size in bytes (for UI display). */
export function getBundledNefSize(): number {
  if (!NEF_BASE64) return 0;
  // Each base64 char encodes 6 bits; total bytes = floor(len * 3 / 4) minus padding.
  const padding = (NEF_BASE64.match(/=/g) || []).length;
  return Math.floor(NEF_BASE64.length * 3 / 4) - padding;
}

// ---------- helpers ----------

function stripHex(s: string): string {
  return s.startsWith('0x') ? s.slice(2) : s;
}

function toScriptHash(addrOrHash: string): string {
  const s = addrOrHash.trim();
  if (s.startsWith('0x') && s.length === 42) return s.toLowerCase();
  // Treat as Neo3 address.
  return '0x' + wallet.getScriptHashFromAddress(s);
}

function base64ToHex(b64: string): string {
  // Browser path: atob → string of latin-1 bytes → hex
  const bin = atob(b64);
  let out = '';
  for (let i = 0; i < bin.length; i++) {
    out += bin.charCodeAt(i).toString(16).padStart(2, '0');
  }
  return out;
}
