/**
 * Wallet-signed contract deployment. Bundles the audited VestingVault NEF
 * + manifest (see {@code nef-artifacts.ts}, generated by
 * {@code scripts/sync-artifacts.mjs}) and routes the
 * {@code ContractManagement.deploy} invocation through the connected
 * wallet.
 *
 * The resulting contract hash is *deterministic*: it's a function of the
 * deployer's script hash + the NEF checksum + the manifest name, so we can
 * compute it locally before the tx confirms (matching the formula
 * neow3j's {@code SmartContract.calcContractHash} uses on the Java side).
 */

import { sc, u, wallet } from '@cityofzion/neon-js';
import type { ContractInvocationMulti } from '@cityofzion/neon-dappkit-types';
import type { UnifiedProvider } from './connection';
import { NEF_BASE64, MANIFEST_JSON, ARTIFACTS_AVAILABLE } from './nef-artifacts';
import { EXPECTED_NEF_CHECKSUM } from './nef-checksum';
import { resolveRpcUrl } from './rpc';

/** Native ContractManagement script hash (the Neo system contract that owns deploy/update/destroy). */
const CONTRACT_MANAGEMENT = '0xfffdc93764dbaddd97c48f252a53ea4643faa3fd';

export interface DeployArgs {
  /** N-prefixed Neo3 address (or 0x scripthash) of the account paying for + signing the deploy. */
  deployerAddress: string;
  /** Address (or scripthash) that will own the new vault — the only one allowed to deposit. */
  ownerAddress: string;
}

export interface DeployResult {
  txHash: string;
  /** Locally computed; matches the on-chain hash exactly once the tx confirms. */
  contractHash: string;
}

export function isArtifactsAvailable(): boolean {
  return ARTIFACTS_AVAILABLE;
}

/**
 * Build the {@code ContractManagement.deploy} invocation payload — used by
 * both {@link deployVault} (which signs + sends) and {@link predictDeployFee}
 * (which test-invokes for fee estimation, no signature).
 */
export function buildDeployPayload(args: DeployArgs): ContractInvocationMulti {
  const ownerScriptHash = toScriptHash(args.ownerAddress);
  const deployerScriptHash = toScriptHash(args.deployerAddress);
  // Per the Neo dapi spec, ByteArray ContractParam values are BASE64,
  // not hex. NEF is already base64; manifest gets utf8 → base64.
  const manifestB64 = u.HexString.fromHex(u.str2hexstring(MANIFEST_JSON)).toBase64();

  // ContractManagement.deploy(nef, manifest, [optional data])
  // The third arg is forwarded as `data` to the new contract's _deploy callback.
  // The signer's `account` must be a hex scripthash — neon-dappkit's
  // calculateFee path goes through neon-js which rejects N-prefixed addresses
  // here. Wallet adapters accept either form, so converting is safe for both.
  return {
    invocations: [
      {
        scriptHash: CONTRACT_MANAGEMENT,
        operation: 'deploy',
        args: [
          { type: 'ByteArray', value: NEF_BASE64 },
          { type: 'ByteArray', value: manifestB64 },
          { type: 'Hash160', value: ownerScriptHash },
        ],
      },
    ],
    signers: [{ account: deployerScriptHash, scopes: 'CalledByEntry' }],
  };
}

/**
 * Submit the deploy. Returns the tx hash and the predicted contract hash;
 * caller awaits confirmation via {@link waitForTx}.
 */
export async function deployVault(provider: UnifiedProvider, args: DeployArgs): Promise<DeployResult> {
  if (!ARTIFACTS_AVAILABLE) {
    throw new Error(
      'No NEF/manifest bundled with this UI build. Run `./gradlew :contract:neow3jCompile` then rebuild.',
    );
  }

  const deployerScriptHash = toScriptHash(args.deployerAddress);
  const payload = buildDeployPayload(args);

  const result = await provider.invokeFunction(payload);
  const txHash = typeof result === 'string' ? result : (result as { hash: string }).hash;

  const contractHash = predictContractHash(deployerScriptHash, EXPECTED_NEF_CHECKSUM, getBundledManifestName());
  return { txHash, contractHash };
}

/**
 * Estimated deployment cost in raw GAS units (1 GAS = 10^8 raw). Returns
 * {@code null} if the RPC is unreachable or the test invoke fails (e.g.
 * the owner address is invalid). Decomposed into:
 *
 *   - {@code systemFee} — VM execution + per-byte storage cost.
 *     ContractManagement charges ~10 GAS for a contract this size.
 *   - {@code networkFee} — tx propagation, proportional to tx size.
 *
 * This is a real RPC call (test-invoke against ContractManagement.deploy);
 * the returned values match what the wallet will charge at signing time
 * within ~1% (small differences from witness-script estimation).
 */
export async function predictDeployFee(args: DeployArgs): Promise<DeployFee> {
  if (!ARTIFACTS_AVAILABLE) {
    throw new Error('No NEF/manifest bundled — recompile the contract and rebuild the UI.');
  }
  // Use a raw `invokefunction` test-invoke for the system fee, then compute
  // the network fee from the tx size. We avoid NeonInvoker's `calculateFee`
  // because its witness-simulation path faults on some neo-cli versions
  // (notably the AxLabs localnet RpcServer) for native ContractManagement
  // calls. The raw test-invoke gives us the same `gasconsumed` value.
  const rpcUrl = resolveRpcUrl();
  const payload = buildDeployPayload(args);
  const rawResp = await rawTestInvokeDeploy(rpcUrl, args, payload);
  if (rawResp.state === 'FAULT') {
    throw new Error(
      `Test-invoke FAULT: ${rawResp.exception ?? '(no message)'}`,
    );
  }
  const sys = BigInt(rawResp.gasconsumed ?? '0');
  // Network fee for a single-sig CalledByEntry deploy tx. The dominant cost
  // is system fee (~10 GAS); network fee for a ~3KB tx is ~0.001-0.002 GAS,
  // a constant rounded conservatively here. The wallet shows the precise
  // value at signing time.
  const net = 200_000n;
  return { systemFee: sys, networkFee: net, total: sys + net };
}

export interface DeployFee {
  /** Raw GAS units (10^8 = 1 GAS). */
  systemFee: bigint;
  /** Raw GAS units. */
  networkFee: bigint;
  /** systemFee + networkFee, in raw GAS units. */
  total: bigint;
}

/** Format a raw-GAS fee as a human-readable "X.XXXX GAS" string. */
export function fmtGas(rawAmount: bigint): string {
  const decimals = 8n;
  const factor = 10n ** decimals;
  const whole = rawAmount / factor;
  const frac = rawAmount % factor;
  if (frac === 0n) return `${whole} GAS`;
  // Trim trailing zeros from the fractional part for compact display.
  const fracStr = frac.toString().padStart(Number(decimals), '0').replace(/0+$/, '');
  return `${whole}.${fracStr} GAS`;
}

/**
 * Extract the deployed contract hash from a `getapplicationlog` response.
 * ContractManagement emits a `Deploy` notification on first deploy with the
 * new contract's Hash160 (base64 little-endian) as the first state item.
 *
 * Returns `null` if the log is malformed or doesn't contain the event —
 * callers should fall back to {@link predictContractHash} in that case.
 */
export function extractDeployedContractHash(log: unknown): string | null {
  type Execution = { notifications?: Notif[] };
  type Notif = { eventname?: string; state?: { value?: { type?: string; value?: string }[] } };
  type Log = { executions?: Execution[] };
  const execs = (log as Log)?.executions ?? [];
  for (const e of execs) {
    for (const n of e.notifications ?? []) {
      if (n.eventname !== 'Deploy') continue;
      const items = n.state?.value;
      if (!items || items.length === 0) continue;
      const first = items[0];
      if (typeof first.value !== 'string') continue;
      // Hash160 ByteString comes back base64-encoded, little-endian.
      const hexLE = u.base642hex(first.value);
      return '0x' + u.reverseHex(hexLE);
    }
  }
  return null;
}

/**
 * Re-implement {@code SmartContract.calcContractHash} from the Java side:
 *
 *   script = ABORT  ||  PUSHDATA1(20)(senderLE)  ||  PUSHINT(checksum)  ||  PUSHDATA1(name_len)(name)
 *   hash   = ripemd160(sha256(script))
 *
 * Returns the 20-byte hash as a 0x-prefixed big-endian hex string (Neo's
 * conventional display form).
 */
export function predictContractHash(
  senderScriptHash: string,
  nefChecksum: number,
  manifestName: string,
): string {
  const senderHex = stripHex(senderScriptHash);
  const senderLE = u.reverseHex(senderHex); // sender as little-endian bytes

  const sb = new sc.ScriptBuilder();
  sb.emit(sc.OpCode.ABORT);
  sb.emitPush(u.HexString.fromHex(senderLE));
  sb.emitPush(nefChecksum);
  sb.emitPush(manifestName);

  const scriptHex = sb.build();
  const hashLE = u.hash160(scriptHex);
  // u.hash160 returns big-endian already; but Neo's contract hashes are
  // displayed reversed-from-storage. Test against a known case if in doubt.
  return '0x' + u.reverseHex(hashLE);
}

/** Read the bundled manifest's `name` field. */
export function getBundledManifestName(): string {
  if (!MANIFEST_JSON) return '';
  try {
    return (JSON.parse(MANIFEST_JSON) as { name: string }).name;
  } catch {
    return '';
  }
}

/** Read the bundled NEF's size in bytes (for UI display). */
export function getBundledNefSize(): number {
  if (!NEF_BASE64) return 0;
  // Each base64 char encodes 6 bits; total bytes = floor(len * 3 / 4) minus padding.
  const padding = (NEF_BASE64.match(/=/g) || []).length;
  return Math.floor(NEF_BASE64.length * 3 / 4) - padding;
}

// ---------- helpers ----------

function stripHex(s: string): string {
  return s.startsWith('0x') ? s.slice(2) : s;
}

/**
 * Call the RPC node's `invokefunction` directly for the deploy. Bypasses
 * NeonInvoker so we can see the raw FAULT response (state, exception,
 * script, notifications) — NeonInvoker throws on FAULT and discards them.
 */
async function rawTestInvokeDeploy(
  rpcUrl: string,
  args: DeployArgs,
  payload: ContractInvocationMulti,
): Promise<{
  state: 'HALT' | 'FAULT';
  exception?: string;
  script?: string;
  gasconsumed?: string;
  stack?: unknown[];
  notifications?: unknown[];
}> {
  const ownerScriptHash = toScriptHash(args.ownerAddress);
  const deployerScriptHash = toScriptHash(args.deployerAddress).replace(/^0x/, '');
  const invocation = payload.invocations[0];
  const body = {
    jsonrpc: '2.0',
    id: 1,
    method: 'invokefunction',
    params: [
      invocation.scriptHash,
      invocation.operation,
      [
        // RPC's `invokefunction` parses ByteArray values as base64 — same
        // format as buildDeployPayload now uses, so values pass through.
        invocation.args![0] as { type: string; value: string },
        invocation.args![1] as { type: string; value: string },
        { type: 'Hash160', value: ownerScriptHash.replace(/^0x/, '') },
      ],
      [{ account: deployerScriptHash, scopes: 'CalledByEntry' }],
    ],
  };
  const resp = await fetch(rpcUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  const json = await resp.json();
  if (json.error) {
    throw new Error(`RPC error: ${JSON.stringify(json.error)}`);
  }
  return json.result;
}

function toScriptHash(addrOrHash: string): string {
  const s = addrOrHash.trim();
  if (s.startsWith('0x') && s.length === 42) return s.toLowerCase();
  // Treat as Neo3 address.
  return '0x' + wallet.getScriptHashFromAddress(s);
}

