// AUTO-GENERATED by scripts/sync-checksum.mjs — do not edit by hand.
// Derived from /home/yannick/workspace/smartargs/neovest/contract/build/neow3j/VestingVault.nef. Re-runs automatically before every `npm run dev` and `npm run build`.

/**
 * Last 4 bytes of `VestingVault.nef` (little-endian uint32). The UI compares
 * this against the deployed contract's NEF checksum (fetched via RPC) to
 * decide the "Verified" badge — see lib/verification.ts.
 */
export const EXPECTED_NEF_CHECKSUM = 3551126892;
