// AUTO-GENERATED by scripts/sync-checksum.mjs — do not edit by hand.
// Derived from contract/build/neow3j/VestingVault.nef. Re-runs automatically before every `npm run dev` and `npm run build`.

/**
 * SHA-256 of the `VestingVault.nef` script bytes — the authoritative
 * commitment the UI uses to decide the "Verified" badge. The deployed
 * contract's script (fetched via RPC) is hashed the same way and compared
 * byte-for-byte equivalent. Empty string means the NEF wasn't compiled at
 * build time, in which case verification falls back to the checksum. See
 * lib/verification.ts.
 */
export const EXPECTED_NEF_SCRIPT_SHA256: string = 'a8eab27b51f33058e88a0157aaf90d3adfd9344a934fe12180164129a63a98db';

/**
 * Last 4 bytes of `VestingVault.nef` (little-endian uint32). Only a 32-bit
 * value and therefore NOT collision-resistant — used as a fast pre-filter
 * and as a fallback when an RPC node omits the script from getcontractstate.
 * Never the sole basis for "Verified".
 */
export const EXPECTED_NEF_CHECKSUM = 1585108054;
